#eureka:
#  server:
#    renewal-threshold-update-interval-ms: 60000
#    eviction-interval-timer-in-ms: 60000
#  instance:
#    lease-expiration-duration-in-seconds: 90
#    lease-renewal-interval-in-seconds: 30